[phases.setup]
nixPkgs = ["php84", "php84Extensions.pdo_pgsql", "php84Extensions.pgsql"]

[phases.install]
cmds = ["composer update --no-dev --optimize-autoloader --no-interaction"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"
